// <auto-generated />
using System;
using AnotadorGymAppApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnotadorGymAppApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117184219_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnotadorGymAppApi.Entities.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RutinaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrecuenciaPorGrupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TiempoPorSesion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RutinaId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaDia", b =>
                {
                    b.Property<int>("RutinaDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RutinaDiaId"));

                    b.Property<string>("NombreRutinaDia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RutinaSemanaId")
                        .HasColumnType("integer");

                    b.HasKey("RutinaDiaId");

                    b.HasIndex("RutinaSemanaId");

                    b.ToTable("RutinaDias");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaEjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RutinaEjercicioId"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer");

                    b.Property<int>("RutinaDiaId")
                        .HasColumnType("integer");

                    b.HasKey("RutinaEjercicioId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaDiaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaSemana", b =>
                {
                    b.Property<int>("RutinaSemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RutinaSemanaId"));

                    b.Property<string>("NombreSemana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.HasKey("RutinaSemanaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaSemanas");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaSerie", b =>
                {
                    b.Property<int>("RutinaSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RutinaSerieId"));

                    b.Property<TimeSpan?>("Descanso")
                        .HasColumnType("interval");

                    b.Property<int?>("Porcentaje1RM")
                        .HasColumnType("integer");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("RutinaEjercicioId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("RutinaSerieId");

                    b.HasIndex("RutinaEjercicioId");

                    b.ToTable("RutinaSeries");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("integer");

                    b.Property<int>("MusculoPrimarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EjercicioId");

                    b.HasIndex("GrupoMuscularId");

                    b.HasIndex("MusculoPrimarioId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.GrupoMuscular", b =>
                {
                    b.Property<int>("GrupoMuscularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GrupoMuscularId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GrupoMuscularId");

                    b.ToTable("GrupoMusculares");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.Musculos", b =>
                {
                    b.Property<int>("MusculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MusculoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MusculoId");

                    b.ToTable("Musculos");
                });

            modelBuilder.Entity("EjercicioMusculos", b =>
                {
                    b.Property<int>("EjerciciosSecundariosEjercicioId")
                        .HasColumnType("integer");

                    b.Property<int>("MusculosSecundariosMusculoId")
                        .HasColumnType("integer");

                    b.HasKey("EjerciciosSecundariosEjercicioId", "MusculosSecundariosMusculoId");

                    b.HasIndex("MusculosSecundariosMusculoId");

                    b.ToTable("EjercicioMusculoSecundarios", (string)null);
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaDia", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Entities.RutinaSemana", "RutinaSemana")
                        .WithMany("Dias")
                        .HasForeignKey("RutinaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaSemana");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaEjercicio", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Models.Ejercicio", "Ejercicio")
                        .WithMany("RutinasEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymAppApi.Entities.RutinaDia", "RutinaDia")
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("RutinaDia");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaSemana", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Entities.Rutina", "Rutina")
                        .WithMany("Semanas")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaSerie", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Entities.RutinaEjercicio", "RutinaEjercicio")
                        .WithMany("Series")
                        .HasForeignKey("RutinaEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaEjercicio");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.Ejercicio", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Models.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Ejercicios")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymAppApi.Models.Musculos", "MusculoPrimario")
                        .WithMany("EjerciciosPrimarios")
                        .HasForeignKey("MusculoPrimarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");

                    b.Navigation("MusculoPrimario");
                });

            modelBuilder.Entity("EjercicioMusculos", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Models.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjerciciosSecundariosEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymAppApi.Models.Musculos", null)
                        .WithMany()
                        .HasForeignKey("MusculosSecundariosMusculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.Rutina", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaDia", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaEjercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Entities.RutinaSemana", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.Ejercicio", b =>
                {
                    b.Navigation("RutinasEjercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.GrupoMuscular", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Models.Musculos", b =>
                {
                    b.Navigation("EjerciciosPrimarios");
                });
#pragma warning restore 612, 618
        }
    }
}
