// <auto-generated />
using System;
using AnotadorGymAppApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnotadorGymAppApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704204051_AddEntrenamientoEjercicioSerie")]
    partial class AddEntrenamientoEjercicioSerie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.EjercicioEntrenado", b =>
                {
                    b.Property<int>("EjercicioEntrenadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjercicioEntrenadoId"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("EntrenamientoId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("EjercicioEntrenadoId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("EntrenamientoId");

                    b.ToTable("EjercicioEntrenado");
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.Entrenamiento", b =>
                {
                    b.Property<int>("EntrenamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntrenamientoId"));

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EntrenamientoId");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("Entrenamiento");
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.SerieEntrenada", b =>
                {
                    b.Property<int>("SerieEntrenadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerieEntrenadaId"));

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<int?>("DescansoSegundos")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioEntrenadoId")
                        .HasColumnType("int");

                    b.Property<bool>("FuePR")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("RPE")
                        .HasColumnType("int");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.HasKey("SerieEntrenadaId");

                    b.HasIndex("EjercicioEntrenadoId");

                    b.ToTable("SerieEntrenada");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int");

                    b.Property<int>("MusculoPrimarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlVideo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjercicioId");

                    b.HasIndex("GrupoMuscularId");

                    b.HasIndex("MusculoPrimarioId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.GrupoMuscular", b =>
                {
                    b.Property<int>("GrupoMuscularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoMuscularId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrupoMuscularId");

                    b.ToTable("GrupoMusculares");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.Musculos", b =>
                {
                    b.Property<int>("MusculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusculoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusculoId");

                    b.ToTable("Musculos");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrecuenciaPorGrupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiempoPorSesion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RutinaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaDia", b =>
                {
                    b.Property<int>("RutinaDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaDiaId"));

                    b.Property<string>("NombreRutinaDia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("int");

                    b.Property<int>("RutinaSemanaId")
                        .HasColumnType("int");

                    b.HasKey("RutinaDiaId");

                    b.HasIndex("RutinaSemanaId");

                    b.ToTable("RutinaDias");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaEjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaEjercicioId"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("RutinaDiaId")
                        .HasColumnType("int");

                    b.HasKey("RutinaEjercicioId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaDiaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaSemana", b =>
                {
                    b.Property<int>("RutinaSemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaSemanaId"));

                    b.Property<string>("NombreSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("int");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.HasKey("RutinaSemanaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaSemanas");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaSerie", b =>
                {
                    b.Property<int>("RutinaSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaSerieId"));

                    b.Property<TimeSpan?>("Descanso")
                        .HasColumnType("time");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("int");

                    b.Property<int?>("Porcentaje1RM")
                        .HasColumnType("int");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("RutinaEjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("RutinaSerieId");

                    b.HasIndex("RutinaEjercicioId");

                    b.ToTable("RutinaSeries");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("invitado");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EjercicioMusculoSecundarios", b =>
                {
                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("MusculoId")
                        .HasColumnType("int");

                    b.HasKey("EjercicioId", "MusculoId");

                    b.HasIndex("MusculoId");

                    b.ToTable("EjercicioMusculoSecundarios", (string)null);
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.EjercicioEntrenado", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Ejercicio.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.Entrenamiento", "Entrenamiento")
                        .WithMany("Ejercicios")
                        .HasForeignKey("EntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Entrenamiento");
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.Entrenamiento", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Usuario.Usuario", "Usuario")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.SerieEntrenada", b =>
                {
                    b.HasOne("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.EjercicioEntrenado", "EjercicioEntrenado")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioEntrenadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioEntrenado");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.Ejercicio", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Ejercicio.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Ejercicios")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Ejercicio.Musculos", "MusculoPrimario")
                        .WithMany("EjerciciosPrimarios")
                        .HasForeignKey("MusculoPrimarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");

                    b.Navigation("MusculoPrimario");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaDia", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaSemana", "RutinaSemana")
                        .WithMany("Dias")
                        .HasForeignKey("RutinaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaSemana");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaEjercicio", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Ejercicio.Ejercicio", "Ejercicio")
                        .WithMany("RutinasEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaDia", "RutinaDia")
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("RutinaDia");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaSemana", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Rutina.Rutina", "Rutina")
                        .WithMany("Semanas")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaSerie", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaEjercicio", "RutinaEjercicio")
                        .WithMany("Series")
                        .HasForeignKey("RutinaEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaEjercicio");
                });

            modelBuilder.Entity("EjercicioMusculoSecundarios", b =>
                {
                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Ejercicio.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymAppApi.Domain.Entities.Ejercicio.Musculos", null)
                        .WithMany()
                        .HasForeignKey("MusculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.EjercicioEntrenado", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("AnotadorGymApp.Api.Domain.Entities.Entrenamiento.Entrenamiento", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.Ejercicio", b =>
                {
                    b.Navigation("RutinasEjercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.GrupoMuscular", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Ejercicio.Musculos", b =>
                {
                    b.Navigation("EjerciciosPrimarios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.Rutina", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaDia", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaEjercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Rutina.RutinaSemana", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("AnotadorGymAppApi.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.Navigation("Entrenamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
